export const CONSTANTS = {
   HOME: '/',
   NUTRIENTS: '/nutrients',
   ADD_NUTRIENT_URL: '/api/add-nutrient',
   DELETE_NUTRIENT_URL: '/api/delete-nutrient',
   UPDATE_NUTRIENT_URL: '/api/update-nutrient',
   UPDATE_SETTINGS_URL: '/api/update-settings',
   AUTH_URL: '/api/auth',
   ADMIN: 'admin@test.com',
   DCN: 'Daily Calorie Need',
   WEIGHT: 'Weight',
   FAT_RATIO: 'Fat Ratio',
   FITNESS_GOAL: 'Fitness Goal',
   WEIGHT_GAIN: 'Weight Gain',
   WEIGHT_LOSS: 'Weight Loss',
   GET: 'GET',
   POST: 'POST',
   PUT: 'PUT',
   DELETE: 'DELETE',
   DELAY: 300
};